//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by doner.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_DONER_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDI_DONER			107
#define IDI_SMALL				108
#define IDC_DONER			109
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1

// menu define
#define IDM_FILE_NEW		110
#define IDM_FILE_OPEN		111
#define IDM_FILE_SAVE		112
#define IDM_FILE_IMPORT		113
#define IDM_FILE_EXIT		114
#define IDM_EDIT_UNDO		115
#define IDM_EDIT_REDO		116
#define IDM_SCENE_PAGE_LAST	117
#define IDM_SCENE_PAGE_NEXT 118
#define IDM_SCENE_PAGE_DELETECURRENT    119
#define IDM_SCENE_PAGE_ADDBLANK     120
#define IDM_SCENE_PAGE_DUPLICATE    121
#define IDM_SCENE_PAGE_COPY 122
#define IDM_SCENE_PAGE_CUT  123
#define IDM_SCENE_PAGE_PASTE    124
#define IDM_SCENE_LIST      125
#define IDM_SCENE_BOOKMARK_MARK 126
#define IDM_SCENE_BOOKMARK_LIST 127
#define IDM_SCENE_CAST_LIST 128
#define IDM_SCENE_CAST_ADDCAST  129
#define IDM_SCENE_CAST_DELETECAST   130
#define IDM_SCENE_CAST_ADDTEXTBOX   131
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
